### PR TITLE
Fix #54 Added Ios app store logo to read me

### LINKED ISSUE #54: iOS store link to redme
Please add an iOS store link to Redme.
The button should look like this
image
There is a common link for the image, please find it from other open-source projects.

Please ask for the app store link when starting this issue.

### PR DESCRIPTION
**Pull request by Abhinav-gh**
Fix issue #54 
I've added the App Store icon using an official badge from Apple Media Services.

### CODE REVIEW

**Comment by Abhinav-gh** [comment]
Hey! I've added the iOS icon while maintaining the table alignment. Can you please review it? I'm new to open source, so I apologize for any inconvenience caused. I am willing to hear your review and feedback if any. Thanks!

**Comment by guyluz11** [comment]
Hey @Abhinav-gh 
It good to see you around, all people are welcome to contribute and it is nice to see that you have recently joined to open source :).

In the preview of your code it shows me that the buttons are not in the same row, I prefer them to be in the same row.

image

**Comment by Abhinav-gh** [comment]
image
Done! Please let me know if you would like to adjust the alignment or modify any other styling for the two logos.

**Review by guyluz11 — APPROVED** [review]

**Comment by guyluz11** [comment]
@Abhinav-gh 
Can you comment on the issue?, just say something like 

Can I work on that?

**Comment by guyluz11** [comment]
Thanks for the pr
Feel free to star the project :D

**Pull request merged**
